### ISSUE TITLE
Using taggedPosts with an offset

### ISSUE THREAD

**Issue by dement6d** [tumblr/tumblr.js#110]
Is this possible? It doesn't seem to work and gives me the same list of posts i would get without using the offset options
It works for `blogPosts` but not for `taggedPosts`
Here is my code:
```js
client.taggedPosts(tags, { offset: 20 }, function(err, resp) {
        for (let i = 0; i < resp.length; i++) {
            console.log(`${resp[i].slug} - ${resp[i].post_url}`)
        }
    })
```
I just found out there is a 'before' option, but i don't fully understand what it does and how to use it, is there any examples?

**Comment by sirreal** [comment]
[According to the API docs, there's no `offset` for this endpoint.](https://www.tumblr.com/docs/en/api/v2#tagged--get-posts-with-tag)

It does accept a `before` parameter:

> The timestamp of when you'd like to see posts before. If the Tag is a "featured" tag, use the "featured_timestamp" on the post object for pagination.

Where _timestamp_ means "number of seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)".

For pagination (to get the next batch of posts), you should be able to look at the `timestamp` on the posts in your response and use that as the `before` for the next request.
