### ISSUE TITLE
Invalid baseUrl

### ISSUE THREAD

**Issue by tianBreznik** [tumblr/tumblr.js#198]
I create the client with only the consumer_key and consumer_secret fields filled out and the tokens left out, as I don't need them and I get the type error "Invalid baseUrl option provided." - I can't seem to find anything about this issue documented anywhere. Could someone point me in the direction of quickly resolving this ?

**Comment by tianBreznik** [comment]
I should also mention, that I am working in ES6, so I am importing the module, not requiring it. Could this somehow cause the baseUrl error?

**Comment by sirreal** [comment]
The library doesn't officially support Node 14. Node 14's end-of-life was 2023-04-30. I'll close this because it seems to be due to an unsupported Node version.

While we don't support Node 14, I will say that 14.15.4 is an old release within the 14 line, the latest being 14.21.3. With 14.21.3 I don't see any issues with [the same test code I shared above](https://github.com/tumblr/tumblr.js/issues/198#issuecomment-1713500672). If you can't upgrade to a supported Node version, maybe at least getting onto a more recent v14 release would help.

> I am importing the module, not requiring it.

That shouldn't be an issue, the integration tests are ES modules and don't have any issues:

https://github.com/tumblr/tumblr.js/blob/0d66f3c159ef00a73b49f000b29e98aa1614396e/integration/read-only.mjs#L2

**Comment by tianBreznik** [comment]
Hi! I updated to node 18 and the invalid baseUrl error persists in the browser, whereas when running the code you provided with my consumer key and secret the error becomes that of authentication:
`TypeError: Provide consumer_key or all oauth credentials. Invalid token provided.`

**Comment by sirreal** [comment]
It sounds like it's working correctly in Node 18. You'll either need to provide _only_ the `consumer_key`, or all four of the required oauth credentials (`consumer_key`, `consumer_secret`, `token`, and `token_secret`). You should be able to get that information from https://www.tumblr.com/oauth/apps or https://api.tumblr.com/console/calls/user/info.

---

[As mentioned in the README](https://github.com/tumblr/tumblr.js#in-the-browser), this library isn't intended for in-browser use. That's something we could work on, however, if folks are interested. If you are interested, please open a new issue for that and we can consider it and start to understand the demand for that.

**Comment by tianBreznik** [comment]
Hi! I tried my consumer_key and secret on the api console, and it looks like the credentials are invalid, since I receive a bad request error, but I'm puzzled as to why. Is my application not registered or is has it not been processed? 
<img width="602" alt="Screenshot 2023-09-15 at 16 26 23" src="https://github.com/tumblr/tumblr.js/assets/37045546/fb16a7c5-449f-470c-ac3a-9548d09bee78">
I think my application clearly is registered, but something else is going on. Could I contact someone from support to check?

**Comment by sirreal** [comment]
That may be a good place to start, you can contact Tumblr support through the help page: https://help.tumblr.com/hc/en-us
