### ISSUE TITLE
Reblog and 401 error

### ISSUE THREAD

**Issue by spookssi** [tumblr/tumblr.js#53]
Hi, im trying to reblog some post but i got the 401 error all the time... 

my code : 

```
var Tok;
var Stok;
var tumblr = require('tumblr.js');
var OAuth = require('oauth').OAuth;
  var oa = new OAuth(
      'http://www.tumblr.com/oauth/request_token',
      'http://www.tumblr.com/oauth/access_token',
      'MY - consumer_key',
      'MY - consumer_secret',
 "1.0A", null, "HMAC-SHA1");

  oa.getOAuthRequestToken(function(error, oauth_token, oauth_token_secret, results) {
    if (error) return 401;
    console.log(oauth_token,oauth_token_secret,results);
    accessToken=oauth_token;
    accessTokenSecret=oauth_token_secret;
    var Tok = oauth_token;
    var Stok= oauth_token_secret;

      if (Tok != undefined) {
        var client = tumblr.createClient({
          consumer_key: 'MY - consumer_key',
          consumer_secret: 'MY - consumer_secret',
          token: "'"+Tok+"'",
          token_secret: "'"+Stok+"'"
        });
      }
        console.log(Stok);

  function init(){
    console.log("-------- INIT --------");
      if (Stok != undefined) {
        client.reblogPost('my-blog.tumblr.com', { id: postId, reblog_key: key }, function (err, data) {
            if (err) {
              console.log(err);
            } else {
            console.log('Reblog -= [OK] =-');
            }
        });
      }
  }
setTimeout(init,5000);
});
```

Im very bad with Callback etc... Can you help me to fix my code please ^^. (Im a newbies with nodejs but i can work with that) Please be Kind ^^.

**Comment by kmck** [comment]
Hi there!

What you're missing is the **user** `token` and `token_secret`. The OAuth tokens you get from `oa.getOAuthRequestToken` don't have any concept of a Tumblr user account, so you're getting 401 errors basically telling you that you don't have permission to post to that blog.

Depending on what you're trying to do specifically, you can either get your own user tokens from the API console or set up the full three-legged OAuth flow, which will go through the Tumblr authorization page and then redirect to the callback URL you set up on your app with the user token and secret when they click "Allow".

#### Getting your own user tokens from the API console

If you're just using your own account to make posts, this is the easy way.

1. Go to https://www.tumblr.com/oauth/apps
2. Find your app and click "Explore API". This will take you through the authorization page on the way to the API console.
3. Click the "Show Keys" button in the top right.
4. Use the keys in `tumblr.createClient`

#### Doing the three-legged OAuth flow

This way is a little more complicated because you'll need to a server to handle redirecting to the Tumblr authorization page and handling the callback URL after the user clicks "Allow", but it's necessary if you're building an app that allows people to post to their Tumblr blogs.

1. Get the OAuth token and secret the way you're doing with `oa.getOAuthRequestToken()`. Hang onto them, because you'll need them later.
2. Redirect to the authorization URL (`https://www.tumblr.com/oauth/authorize?oauth_token=OAUTHTOKEN&oauth_callback=http://YOURCALLBACKURL`) with the OAuth token and secret, which will redirect to the authorization page.
3. The callback URL will get the same `oauth_token` you passed in plus an `oauth_verifier` parameter. Hang onto these too.
4. Now you can get the user token and secret by requesting an access token, which is what gives you permission to make API requests as that user. You can get them  `oa.getOAuthAccessToken(oauthToken, oauthTokenSecret, oauthVerifier, function(userToken, userTokenSecret) { /* your code here ... */ })`
5. In the callback of `oa.getOAuthAccessToken()`, you finally have the user token and secret, so that combined with your consumer key and secret allows you to make fully authenticated requests to the Tumblr API.
6. Make the requests!

**Comment by spookssi** [comment]
HI @kmck Thx for your reply !

I already use my token/secretToken from my API console. But with the reblogPost method J'm getting error 400 bas request.

I use : 

- client.userInfo - no problem
- client.taggedPosts - no problem
- client.reblogPost - error 400 bad request but all my function is alright... i'm stuck :/

`function reblogMachine(){

    var randKey = Math.floor((Math.random() * reblogKey.length) + 1);
    var key = reblogKey[randKey];
    var postId = postIdList[randKey];
    var blogName = 'stochastique-blog';

    if (key != undefined){
      client.reblogPost(blogName,{ id: postId, reblog_key: key}, function (err, data) {
                if (err) {
                  throw new Error(err);
                } else {
                  console.log('Reblog -= [OK] =-');
                }
          });
        }
      }`

**Comment by kmck** [comment]
Oh, hmm. A 400 error in that case usually indicates that the post ID and reblog key don't match or are invalid. Could you provide an example pair that you're using?

**Comment by spookssi** [comment]
here a random example :  ID = 146717482224Reblog key = jatue9Yf.

Maybe my list are not synchronised 0_o ! I grap random post with tags and create list of key and id. Maybe there are an error with tag...

**Comment by kmck** [comment]
Odd! That random example just worked for me, no problem. Seems like the ID and reblog key combination are valid, but maybe some of them are mixed up?

If you're not getting the 401, your authentication seems to be fine. You can try this to double-check that the user token/secret are valid:

```js
client.createPost(blogName, {type:'text', body:'test'});
```

Keep in mind that for `client.userInfo` and `client.taggedPosts` it's not actually going to be validating the user token and secret (since they're public read-only routes).

**Comment by spookssi** [comment]
hm...💃
With : client.createPost(blogName, {type:'text', body:'test'});
```
Uncaught TypeError: requestCallback(...) is not a function
API error: 400 Bad Request
```

**Comment by kmck** [comment]
Oh, good call! Didn't think to check that. 😄 

You should be in good shape now, so I'm going to close this. Happy API-ing!
