### ISSUE TITLE
Can tumblr.js be published pre-compiled ? 

### ISSUE THREAD

**Issue by john-raymon** [tumblr/tumblr.js#79]
Tumblr.js node dependencies don't compile when attempting to compile with Create React App. The issue is summarized below. 
_Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years._

**Comment by kmck** [comment]
As far as I know, tumblr.js isn't using any ES6 features, so there shouldn't be anything to compile.

Could you say a little more about how you're trying to integrate tumblr.js with Create React App? Can't say for sure without more details, but you might be running into problems because this library isn't meant to be used in the browser. My guess is that you need to integrate tumblr.js with your backend API instead of the React app. If so, [this tutorial](https://www.fullstackreact.com/articles/using-create-react-app-with-a-server/) might be helpful.

**Comment by InstanceOfMichael** [comment]
> tumblr.js isn't using any ES6 features

I think the main issue is that the API is built on top of `request` and there is not known version of request for the browser that also supports request's oauth helper.
